//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 03:09:26 PM CET 
//


package nl.pczeeuw.ws.countries;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.pczeeuw.ws.countries package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.pczeeuw.ws.countries
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CountryCapitalResponse }
     * 
     */
    public CountryCapitalResponse createCountryCapitalResponse() {
        return new CountryCapitalResponse();
    }

    /**
     * Create an instance of {@link CountryAddedToDbResponse }
     * 
     */
    public CountryAddedToDbResponse createCountryAddedToDbResponse() {
        return new CountryAddedToDbResponse();
    }

    /**
     * Create an instance of {@link CountryByNameRequest }
     * 
     */
    public CountryByNameRequest createCountryByNameRequest() {
        return new CountryByNameRequest();
    }

    /**
     * Create an instance of {@link CountryNameResponse }
     * 
     */
    public CountryNameResponse createCountryNameResponse() {
        return new CountryNameResponse();
    }

    /**
     * Create an instance of {@link AddCountryToDBRequest }
     * 
     */
    public AddCountryToDBRequest createAddCountryToDBRequest() {
        return new AddCountryToDBRequest();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link CountryPopByNameRequest }
     * 
     */
    public CountryPopByNameRequest createCountryPopByNameRequest() {
        return new CountryPopByNameRequest();
    }

    /**
     * Create an instance of {@link CountryNameByCapitalRequest }
     * 
     */
    public CountryNameByCapitalRequest createCountryNameByCapitalRequest() {
        return new CountryNameByCapitalRequest();
    }

    /**
     * Create an instance of {@link CountryPopResponse }
     * 
     */
    public CountryPopResponse createCountryPopResponse() {
        return new CountryPopResponse();
    }

    /**
     * Create an instance of {@link CountryRespone }
     * 
     */
    public CountryRespone createCountryRespone() {
        return new CountryRespone();
    }

}
