//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 09:46:34 AM CET 
//


package nl.pczeeuw.ws.countries;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.pczeeuw.ws.countries package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AllCountriesRequest_QNAME = new QName("http://pczeeuw.nl/ws/countries", "allCountriesRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.pczeeuw.ws.countries
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CountryAddedToDbResponse }
     * 
     */
    public CountryAddedToDbResponse createCountryAddedToDbResponse() {
        return new CountryAddedToDbResponse();
    }

    /**
     * Create an instance of {@link CountryByNameRequest }
     * 
     */
    public CountryByNameRequest createCountryByNameRequest() {
        return new CountryByNameRequest();
    }

    /**
     * Create an instance of {@link AddCountryToDBRequest }
     * 
     */
    public AddCountryToDBRequest createAddCountryToDBRequest() {
        return new AddCountryToDBRequest();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link AllCountriesResponse }
     * 
     */
    public AllCountriesResponse createAllCountriesResponse() {
        return new AllCountriesResponse();
    }

    /**
     * Create an instance of {@link CountryResponse }
     * 
     */
    public CountryResponse createCountryResponse() {
        return new CountryResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pczeeuw.nl/ws/countries", name = "allCountriesRequest")
    public JAXBElement<Object> createAllCountriesRequest(Object value) {
        return new JAXBElement<Object>(_AllCountriesRequest_QNAME, Object.class, null, value);
    }

}
