//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 09:46:34 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pczeeuw.nl/ws/countries", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.pczeeuw.ws.countries;
